### ISSUE TITLE
Django Tutorial

### ISSUE THREAD

**Issue by Xiro234** [bnguye1/Fumble#1]
Sizing: 8 Points

Do the Django tutorial (https://docs.djangoproject.com/en/4.0/intro/tutorial01/) up through part 7.

**Comment by bnguye1** [comment]
I finished the Django tutorial and uploaded the project to the repository because we'll probably need to do this again later.

**Comment by Xiro234** [comment]
Finished Django tutorial.

**Comment by lazerw** [comment]
Finished the Django tutorial.

**Comment by nalgreen** [comment]
Finished Django tutorial

**Comment by silverzx** [comment]
Finished Django tutorial
