### ISSUE TITLE
Map Interaction

### ISSUE THREAD

**Issue by Xiro234** [bnguye1/Fumble#10]
Experiment with Google Maps API
1. https://developers.google.com/maps/apis-by-platform
2. https://developers.google.com/maps/documentation/embed/get-started
3. Ideally, having this API working would be a blessing.
4. Get map on screen (3)
5. Move camera to some location (will eventually center on the team’s home base, but we don’t have that loaded in the backend yet). (3)
6. Place a marker on the map where the home base is. (3)

**Comment by lazerw** [comment]
completed on iteration 3 (pull request #41)
